[package]
name = "fantasma_circuits"
version = "0.1.0"
edition = "2024_07"

[dependencies]

[dev-dependencies]
cairo_test = "2.9.2"

[cairo]
enable-gas = false

# Library target - circuits are compiled and used by prover
[lib]
